name: DeployToGithubPages
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Publish app
        run: dotnet publish -c Release
      - name: Rewrite base href
        uses: SteveSandersonMS/ghaction-rewrite-base-href@v1
        with:
          html_path: bin/Release/net7.0/publish/wwwroot/index.html
          base_href: /BlazorOnGitHubPages/
      - name: GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v1.5.1
        with:
          target_branch: gh-pages
          build_dir: bin/Release/net7.0/publish/wwwroot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}